//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wada.Data.DesignDepartmentDataBse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public string Id { get; set; }
        public string WorkingNumber { get; set; }
        public string Det { get; set; }
        public string MajorWorkingClassification { get; set; }
        public string MiddleWorkingClassification { get; set; }
        public decimal ManHour { get; set; }
        public string Note { get; set; }
        public string AttendanceId { get; set; }
        public string AchievementProcess { get; set; }
    }
}
