//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wada.Data.DesignDepartmentDataBse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public string Id { get; set; }
        public int EmployeeNumber { get; set; }
        public System.DateTime AchievementDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public string DayOffClassification { get; set; }
        public string Department { get; set; }
    }
}
