//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wada.Data.DesignDepartmentDataBse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnCompanyHoliday
    {
        public System.DateTime HolidayDate { get; set; }
        public bool LegalHoliday { get; set; }
    }
}
