//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wada.Data.OrderManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M作業台帳
    {
        public int 自社NO { get; set; }
        public string 作業NO { get; set; }
        public string 旧作業NO { get; set; }
        public short 年度 { get; set; }
        public int 得意先ID { get; set; }
        public Nullable<System.DateTime> 受注日 { get; set; }
        public Nullable<System.DateTime> EDI納期 { get; set; }
        public Nullable<System.DateTime> 納期 { get; set; }
        public string 納入場所 { get; set; }
        public string カラー { get; set; }
        public string 機種 { get; set; }
        public string 機種コード { get; set; }
        public string 客先担当 { get; set; }
        public string ToolNo { get; set; }
        public string 工程 { get; set; }
        public string 一貫No { get; set; }
        public string コード { get; set; }
        public string シーケンス { get; set; }
        public string ツール { get; set; }
        public string 製作点数 { get; set; }
        public Nullable<int> 個数１ { get; set; }
        public Nullable<int> 個数２ { get; set; }
        public string 単位１ { get; set; }
        public string 単位２ { get; set; }
        public string 発行No { get; set; }
        public Nullable<int> 製作 { get; set; }
        public string オーダー { get; set; }
        public string アイテム { get; set; }
        public string 作理 { get; set; }
        public string ユース { get; set; }
        public Nullable<int> MND1 { get; set; }
        public Nullable<System.DateTime> MNDDate1 { get; set; }
        public Nullable<int> MND2 { get; set; }
        public Nullable<System.DateTime> MNDDate2 { get; set; }
        public string 製作種別 { get; set; }
        public string 図面 { get; set; }
        public string LIFETIME { get; set; }
        public string RefToolNo { get; set; }
        public string 品名 { get; set; }
        public string 板金棚番 { get; set; }
        public Nullable<int> 製作号機1 { get; set; }
        public Nullable<int> 製作号機2 { get; set; }
        public Nullable<int> 責任ショップ { get; set; }
        public string 規格 { get; set; }
        public string 材料ロットNo { get; set; }
        public Nullable<double> 板厚 { get; set; }
        public Nullable<double> W { get; set; }
        public Nullable<double> L { get; set; }
        public Nullable<short> 個数取 { get; set; }
        public Nullable<int> テンプレート借用 { get; set; }
        public Nullable<int> テンプレート返却 { get; set; }
        public string メモ { get; set; }
        public Nullable<System.DateTime> TUpdate { get; set; }
        public string 状態 { get; set; }
        public Nullable<double> 工数 { get; set; }
        public string バーコード { get; set; }
        public Nullable<int> 三工程 { get; set; }
        public string 前状態 { get; set; }
        public Nullable<System.DateTime> 完成日 { get; set; }
        public Nullable<System.DateTime> 請求日 { get; set; }
        public Nullable<System.DateTime> 検収日 { get; set; }
        public string 注文No { get; set; }
        public Nullable<System.DateTime> 予定日 { get; set; }
        public Nullable<decimal> 契約単価 { get; set; }
        public Nullable<decimal> 見積金額 { get; set; }
        public Nullable<decimal> 請求金額 { get; set; }
        public string 材料材質 { get; set; }
        public string マイラー { get; set; }
        public Nullable<System.DateTime> 納品日 { get; set; }
        public string ロット { get; set; }
        public Nullable<System.DateTime> 請求書発行日 { get; set; }
        public Nullable<System.DateTime> 納品書発行日 { get; set; }
        public Nullable<System.DateTime> 仮納品書発行日 { get; set; }
        public Nullable<int> 請求No { get; set; }
        public string 持込者 { get; set; }
        public Nullable<int> 納品書 { get; set; }
        public Nullable<System.DateTime> EDI参照日 { get; set; }
        public Nullable<int> カルテ種類ID { get; set; }
        public Nullable<System.DateTime> 部品明細書作成日 { get; set; }
        public string 部品明細書作成者 { get; set; }
        public Nullable<short> リスク発生確率 { get; set; }
        public Nullable<short> リスク影響度 { get; set; }
        public Nullable<byte> リスク発生確率納期 { get; set; }
        public Nullable<byte> リスク発生確率技術 { get; set; }
        public Nullable<byte> リスク発生確率品質 { get; set; }
        public Nullable<byte> リスク影響度納期 { get; set; }
        public Nullable<byte> リスク影響度技術 { get; set; }
        public Nullable<byte> リスク影響度品質 { get; set; }
        public string リスク実施部門 { get; set; }
        public string リスク管理責任者 { get; set; }
        public Nullable<bool> アイテムの大きさが2000mm以上 { get; set; }
        public Nullable<bool> 溶接加工_表面処理_焼入れ_窒化処理_NC加工プログラム製作等 { get; set; }
        public Nullable<bool> 形状公差_0_05以下 { get; set; }
        public Nullable<bool> 穴交差_0_02以下 { get; set; }
        public Nullable<bool> 過去に実績がない新規発注アイテムまたは加工方法 { get; set; }
    }
}
