//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wada.Data.OrderManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class S社員
    {
        public string 分類 { get; set; }
        public int 社員NO { get; set; }
        public string 氏名 { get; set; }
        public Nullable<int> 所属会社ID { get; set; }
        public Nullable<int> 雇用形態ID { get; set; }
        public Nullable<int> 勤務形態ID { get; set; }
        public Nullable<int> 部署ID { get; set; }
        public Nullable<int> 実績工程ID { get; set; }
        public string フリガナ { get; set; }
        public System.DateTime 生年月日 { get; set; }
        public Nullable<short> 年齢 { get; set; }
        public string 血液型 { get; set; }
        public string 郵便番号 { get; set; }
        public string 住所 { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string 会社携帯番号 { get; set; }
        public string 携帯番号 { get; set; }
        public Nullable<short> 勤続 { get; set; }
        public System.DateTime 入社日 { get; set; }
        public Nullable<int> 勤務地ID { get; set; }
        public Nullable<int> 派遣先ID { get; set; }
        public Nullable<System.DateTime> 派遣終了日 { get; set; }
        public string 役職 { get; set; }
        public string 夏作業服 { get; set; }
        public string 冬作業服 { get; set; }
        public string 作業帽 { get; set; }
        public string 上着サイズ { get; set; }
        public string 上着種類 { get; set; }
        public string ズボンW { get; set; }
        public string ズボン丈 { get; set; }
        public string ジャンパー { get; set; }
        public string Tシャツ { get; set; }
        public string 安全靴 { get; set; }
        public string 通勤手段 { get; set; }
        public string 駐車場 { get; set; }
        public string 通勤距離 { get; set; }
        public string 通勤手当 { get; set; }
        public string 銀行名 { get; set; }
        public string 支店名 { get; set; }
        public string 口座番号 { get; set; }
        public string 基礎年金番号 { get; set; }
        public string 健保番号 { get; set; }
        public string 雇用保険番号 { get; set; }
        public string 備考 { get; set; }
        public Nullable<int> 表示順 { get; set; }
        public string 検索キー { get; set; }
    }
}
